#!/usr/bin/env python3
"""Detect articles that cover a topic the journal has already covered.

Why this exists
---------------
Articles are written by a scheduled job twice a day. The job has no memory of
what it published last week, so it periodically re-covers a subject it has
already done — usually with a slightly different slug, which makes the repeat
invisible to a simple filename check. Eighteen such duplicates accumulated
before anyone noticed.

Two checks run here:

  * exact slug collision — the same slug under two dates in one track. Always
    a duplicate, so this fails the build.

  * near-duplicate — two articles whose titles, summaries and tags overlap
    above a threshold. This is a judgement call, so it is reported but does not
    fail. Genuinely distinct neighbours (Temporal vs Restate, opaque types vs
    match types) will show up here and that is fine.

Usage:

    python3 tools/check_duplicates.py            # report; fail on exact collisions
    python3 tools/check_duplicates.py --ledger   # rewrite TOPICS.md
"""
import argparse
import collections
import glob
import itertools
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n?(.*)\Z", re.S)

# Words too common in this subject matter to signal that two articles overlap.
STOP = set(
    """a an the and or vs to of in for with your you is it on what how why not that
    this as at by from are be can we they its their when where which while into over
    under about actually really just only more most other same than then them these
    those there here so if but do does did done has have had was were will would
    should could may might must one two three using use used make makes made get gets
    guide intro introduction part""".split()
)

SIMILARITY_THRESHOLD = 0.34


def load():
    articles = []
    for path in sorted(glob.glob(os.path.join(ROOT, "_articles", "*", "*.md"))):
        m = FRONT_MATTER.match(open(path, encoding="utf-8").read())
        if not m:
            continue
        fm = yaml.safe_load(m.group(1)) or {}
        articles.append(
            {
                "path": os.path.relpath(path, ROOT),
                "slug": re.sub(r"^\d{4}-\d{2}-\d{2}-", "", os.path.basename(path))[:-3],
                "title": fm.get("title", ""),
                "summary": fm.get("summary", "") or "",
                "tags": set(fm.get("tags") or []),
                "track": fm.get("track", ""),
                "date": str(fm.get("date", "")),
            }
        )
    return articles


def words(a):
    text = (a["title"] + " " + a["summary"]).lower()
    return set(re.findall(r"[a-z0-9][a-z0-9+.#-]{2,}", text)) - STOP


def similarity(a, b, wa, wb):
    """Blend text overlap with tag overlap; both are Jaccard indices."""
    text = len(wa & wb) / len(wa | wb) if (wa | wb) else 0
    tags = len(a["tags"] & b["tags"]) / len(a["tags"] | b["tags"]) if (a["tags"] | b["tags"]) else 0
    return 0.65 * text + 0.35 * tags


def write_ledger(articles):
    """Regenerate TOPICS.md — the list the publishing job should consult before
    choosing what to write about next."""
    by_track = collections.defaultdict(list)
    for a in articles:
        by_track[a["track"]].append(a)

    out = [
        "# Topics already covered",
        "",
        "Generated by `tools/check_duplicates.py --ledger`. Do not edit by hand.",
        "",
        "The publishing job should read this before picking subjects: if a topic",
        "already appears here, either skip it or deliberately extend the existing",
        "article instead of writing a second one.",
        "",
        f"{len(articles)} articles across {len(by_track)} tracks.",
        "",
    ]
    for track in sorted(by_track):
        items = sorted(by_track[track], key=lambda a: a["date"], reverse=True)
        out.append(f"## {track} ({len(items)})")
        out.append("")
        for a in items:
            out.append(f"- `{a['slug']}` — {a['title']} ({a['date']})")
        out.append("")

    path = os.path.join(ROOT, "TOPICS.md")
    open(path, "w", encoding="utf-8").write("\n".join(out))
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ledger", action="store_true", help="rewrite TOPICS.md")
    args = ap.parse_args()

    articles = load()

    if args.ledger:
        print("wrote", os.path.relpath(write_ledger(articles), ROOT))

    # --- exact slug collisions (fatal) ---
    by_slug = collections.defaultdict(list)
    for a in articles:
        by_slug[a["slug"]].append(a)
    collisions = {s: v for s, v in by_slug.items() if len(v) > 1}

    for slug, items in sorted(collisions.items()):
        print(f"DUPLICATE SLUG: {slug}")
        for a in items:
            print(f"    {a['path']}")

    # --- near-duplicates (reported only) ---
    bags = {a["path"]: words(a) for a in articles}
    near = []
    for x, y in itertools.combinations(articles, 2):
        if x["slug"] == y["slug"]:
            continue
        s = similarity(x, y, bags[x["path"]], bags[y["path"]])
        if s >= SIMILARITY_THRESHOLD:
            near.append((s, x, y))
    near.sort(key=lambda t: -t[0])

    if near:
        print(f"\nPossible topic overlap ({len(near)} pair(s), review by hand):")
        for s, x, y in near:
            print(f"  [{s:.2f}] {x['slug']}  <->  {y['slug']}")

    print(f"\nchecked {len(articles)} articles: "
          f"{len(collisions)} exact collision(s), {len(near)} near-duplicate pair(s)")

    if collisions:
        print("\nAn exact slug collision is always a duplicate. Keep the more complete\n"
              "article, port anything unique out of the other, redirect inbound links,\n"
              "and delete the redundant file.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
